In [833]:
from sklearn import datasets,linear_model
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [834]:
space_titan_train = pd.read_csv("train_dim.csv")
space_titan_test = pd.read_csv('submission1226.csv')
space_titan_data = pd.read_csv('test_dim.csv')


In [835]:
space_titan_train_cat = space_titan_train.select_dtypes(object)
space_titan_train_num = space_titan_train.select_dtypes(np.number)
space_titan_train_bool = space_titan_train.select_dtypes(bool)

space_titan_test_cat = space_titan_test.select_dtypes(object)
space_titan_test_num = space_titan_test.select_dtypes(np.number)

space_titan_data_cat = space_titan_data.select_dtypes(object)
space_titan_data_num = space_titan_data.select_dtypes(np.number)

In [836]:
space_titan_train_cat.drop(['PassengerId','Name'],axis=1,inplace = True)

space_titan_test_cat.drop(['PassengerId'],axis=1,inplace = True)

space_titan_data_cat.drop(['PassengerId','Name'],axis=1,inplace = True)

In [837]:
space_titan_train_cat.HomePlanet.fillna(space_titan_train_cat.HomePlanet.value_counts().idxmax(),inplace=True)
space_titan_train_cat.CryoSleep.fillna(space_titan_train_cat.CryoSleep.value_counts().idxmax(),inplace=True)
space_titan_train_cat.Cabin.fillna(space_titan_train_cat.Cabin.value_counts().idxmax(),inplace=True)
space_titan_train_cat.Destination.fillna(space_titan_train_cat.Destination.value_counts().idxmax(),inplace=True)
space_titan_train_cat.VIP.fillna(space_titan_train_cat.VIP.value_counts().idxmax(),inplace=True)


In [838]:
space_titan_data_cat.HomePlanet.fillna(space_titan_train_cat.HomePlanet.value_counts().idxmax(),inplace=True)
space_titan_data_cat.CryoSleep.fillna(space_titan_train_cat.CryoSleep.value_counts().idxmax(),inplace=True)
space_titan_data_cat.Cabin.fillna(space_titan_train_cat.Cabin.value_counts().idxmax(),inplace=True)
space_titan_data_cat.Destination.fillna(space_titan_train_cat.Destination.value_counts().idxmax(),inplace=True)
space_titan_data_cat.VIP.fillna(space_titan_train_cat.VIP.value_counts().idxmax(),inplace=True)

In [839]:
space_titan_train_num.Age.fillna(space_titan_train_num.Age.mean(),inplace=True)
space_titan_train_num.RoomService.fillna(space_titan_train_num.RoomService.mean(),inplace=True)
space_titan_train_num.FoodCourt.fillna(space_titan_train_num.FoodCourt.mean(),inplace=True)
space_titan_train_num.ShoppingMall.fillna(space_titan_train_num.ShoppingMall.mean(),inplace=True)
space_titan_train_num.Spa.fillna(space_titan_train_num.Spa.mean(),inplace=True)
space_titan_train_num.VRDeck.fillna(space_titan_train_num.VRDeck.mean(),inplace=True)


In [840]:
space_titan_data_num.Age.fillna(space_titan_train_num.Age.mean(),inplace=True)
space_titan_data_num.RoomService.fillna(space_titan_train_num.RoomService.mean(),inplace=True)
space_titan_data_num.FoodCourt.fillna(space_titan_train_num.FoodCourt.mean(),inplace=True)
space_titan_data_num.ShoppingMall.fillna(space_titan_train_num.ShoppingMall.mean(),inplace=True)
space_titan_data_num.Spa.fillna(space_titan_train_num.Spa.mean(),inplace=True)
space_titan_data_num.VRDeck.fillna(space_titan_train_num.VRDeck.mean(),inplace=True)

In [841]:
le = LabelEncoder()

space_titan_train_cat = space_titan_train_cat.apply(le.fit_transform)
space_titan_train_bool = space_titan_train_bool.apply(le.fit_transform)

space_titan_data_cat = space_titan_data_cat.apply(le.fit_transform)

In [842]:
space_titan_train_full = pd.concat([space_titan_train_cat, space_titan_train_num,space_titan_train_bool],axis=1)


space_titan_test_full = space_titan_test_num

space_titan_data_full = pd.concat([space_titan_data_cat,space_titan_data_num],axis=1)
space_titan_data_full.head()


HomePlanet  CryoSleep  Cabin  Destination  VIP   Age  RoomService  \
0           0          1   2784            2    0  27.0          0.0   
1           0          0   1867            2    0  19.0          0.0   
2           1          1    257            0    0  31.0          0.0   
3           1          0    259            2    0  38.0          0.0   
4           0          0   1940            2    0  20.0         10.0   

   FoodCourt  ShoppingMall     Spa  VRDeck  
0        0.0           0.0     0.0     0.0  
1        9.0           0.0  2823.0     0.0  
2        0.0           0.0     0.0     0.0  
3     6652.0           0.0   181.0   585.0  
4        0.0         635.0     0.0     0.0

In [843]:
x = space_titan_train_full.drop(['Transported'],axis=1)
y = space_titan_train_full['Transported']

x_train = np.array(x[0:int(len(x))])
y_train = np.array(y[0:int(len(y))])

x_test = np.array(space_titan_data_full[0:int(len(space_titan_data_full))])
y_ans = np.array(space_titan_test_full[0:int(len(space_titan_test_full))])
print(y_ans)


[[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [0]]


In [844]:
RF = RandomForestClassifier()
RF_fit = RF.fit(x_train,y_train)

RF_pred = RF_fit.predict(x_test)
print(RF_pred)
print(accuracy_score(RF_pred,y_ans)*100)

[1 0 1 ... 1 1 1]
87.93546878653261


In [845]:
RF_pred_proba = RF_fit.predict_proba(x_test)
print(RF_pred_proba)

[[0.31 0.69]
 [0.97 0.03]
 [0.   1.  ]
 ...
 [0.05 0.95]
 [0.11 0.89]
 [0.35 0.65]]
